language: node_js
node_js:
  - "4.6.0"
script:
  - echo "Deploying to Firebase Hosting Martin!"
install:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
after_success:
  - ng build
  - firebase deploy --token $FIREBASE_TOKEN
