language: node_js
node_js:
  - "6.10.3"
script:
  - echo: "Deploying to Firebase Hosting Martin!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
